"""Build-time ROM catalog generator for the K10 NES player.

Scans the project's `games/` folder for every `*.nes` file and embeds all of
them into firmware as flash-backed PROGMEM arrays, then emits a small catalog
the menu/main code can iterate. This replaces the old single-ROM `contra_rom.h`.

Outputs (both regenerated each build, but only rewritten when content changes
so incremental builds stay fast):
  - src/rom_catalog.h      struct RomEntry + extern declarations (no data).
                           Include this from any TU that just reads the table.
  - src/rom_catalog_data.h the PROGMEM arrays + the g_roms[]/g_rom_count
                           DEFINITIONS. Include from exactly ONE TU (main.cpp)
                           or you'll get duplicate symbols / duplicated flash.

Two ways to run:
  * Automatically: registered as `extra_scripts` in platformio.ini, so a plain
    `pio run` regenerates the catalog before compiling.
  * Manually:      `python3 tools/gen_rom_catalog.py`
"""

import os
import sys


def _project_root():
    """Project root, resolved three ways for the contexts this script runs in.

    1. Standalone (`python3 tools/...`): ``__file__`` is set.
    2. Imported by PlatformIO/SCons as an extra_script: ``__file__`` is NOT set,
       but the build ``env`` is in this module's globals and exposes the dir.
    3. Fallback: PlatformIO also runs extra_scripts with cwd = project root.
    """
    try:
        return os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    except NameError:
        pass
    env = globals().get("env")
    if env is not None:
        try:
            return env.subst("$PROJECT_DIR")
        except Exception:
            pass
    return os.getcwd()


# Project root = parent of the tools/ dir this file lives in.
ROOT = _project_root()
GAMES = os.path.join(ROOT, "games")
OUT_H = os.path.join(ROOT, "src", "rom_catalog.h")
OUT_DATA_H = os.path.join(ROOT, "src", "rom_catalog_data.h")


def collect_roms():
    """Return (name, abspath) for every .nes in games/, sorted by name."""
    if not os.path.isdir(GAMES):
        return []
    out = []
    for name in os.listdir(GAMES):
        if name.lower().endswith(".nes") and os.path.isfile(os.path.join(GAMES, name)):
            out.append(name)
    out.sort()
    return [(n, os.path.join(GAMES, n)) for n in out]


def display_name(filename):
    """Game label = filename with the .nes extension stripped (case-insensitive)."""
    return filename[:-4] if filename.lower().endswith(".nes") else filename


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def build_headers():
    roms = collect_roms()
    if not roms:
        sys.stderr.write("[gen_rom_catalog] WARNING: no .nes files found in %s\n"
                         % GAMES)

    # ---- rom_catalog.h : types + extern decls (no data, safe in any TU) ----
    hdr = []
    hdr.append("// Auto-generated by tools/gen_rom_catalog.py. Do not edit by hand.")
    hdr.append("// Re-run `pio run` (or the script) after adding/removing ROMs in games/.")
    hdr.append("#pragma once")
    hdr.append("#include <stdint.h>")
    hdr.append("#include <stddef.h>")
    hdr.append("")
    hdr.append("// One entry per .nes in games/. Read g_roms[g_rom_count] via select_game().")
    hdr.append("struct RomEntry")
    hdr.append("{")
    hdr.append("    const char   *name;   // display label (filename minus extension)")
    hdr.append("    const uint8_t *data;  // PROGMEM image, flash-mapped & directly readable")
    hdr.append("    size_t        len;    // image size in bytes")
    hdr.append("};")
    hdr.append("")
    hdr.append("extern const RomEntry g_roms[];")
    hdr.append("extern const size_t   g_rom_count;")
    hdr.append("")
    hdr_text = "\n".join(hdr)

    # ---- rom_catalog_data.h : the big PROGMEM arrays + definitions ----
    d = []
    d.append("// Auto-generated by tools/gen_rom_catalog.py. Do not edit by hand.")
    d.append("// Include this from EXACTLY ONE translation unit (main.cpp) -- it")
    d.append("// defines g_roms/g_rom_count, so a second include = duplicate symbols.")
    d.append("#pragma once")
    d.append("#include \"rom_catalog.h\"")
    d.append("")
    entries = []
    for idx, (name, path) in enumerate(roms):
        with open(path, "rb") as f:
            data = f.read()
        sym = "rom%d_data" % idx
        d.append("// %s (%d bytes)" % (name, len(data)))
        d.append("static const uint8_t %s[] PROGMEM = {" % sym)
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            d.append("  " + ", ".join("0x%02x" % b for b in chunk) + ",")
        d.append("};")
        d.append("")
        entries.append((display_name(name), sym, len(data)))

    d.append("const RomEntry g_roms[] = {")
    if entries:
        for name, sym, ln in entries:
            d.append('  { "%s", %s, %d },' % (c_escape(name), sym, ln))
    else:
        # Zero-ROM placeholder so the array has a valid element; never indexed
        # because g_rom_count == 0 (main.cpp halts before touching the table).
        d.append('  { "", nullptr, 0 },')
    d.append("};")
    d.append("const size_t g_rom_count = %d;" % len(entries))
    d.append("")
    data_text = "\n".join(d)
    return len(entries), hdr_text, data_text


def write_if_changed(path, text):
    """Write only when content differs, so unchanged builds don't force a recompile."""
    old = None
    if os.path.exists(path):
        try:
            with open(path, "r") as f:
                old = f.read()
        except Exception:
            old = None
    if old == text:
        return False
    with open(path, "w") as f:
        f.write(text)
    return True


def main():
    count, hdr_text, data_text = build_headers()
    h_changed = write_if_changed(OUT_H, hdr_text)
    d_changed = write_if_changed(OUT_DATA_H, data_text)
    verb = "wrote" if (h_changed or d_changed) else "unchanged"
    print("[gen_rom_catalog] %s catalog with %d ROM(s): %s, %s"
          % (verb, count,
             os.path.relpath(OUT_H, ROOT),
             os.path.relpath(OUT_DATA_H, ROOT)))


if __name__ == "__main__":
    main()
else:
    # When imported by PlatformIO as an extra_script, generate immediately so
    # the headers exist before any source (which #includes them) is compiled.
    main()
