// Auto-generated by tools/gen_rom_catalog.py. Do not edit by hand.
// Re-run `pio run` (or the script) after adding/removing ROMs in games/.
#pragma once
#include <stdint.h>
#include <stddef.h>

// One entry per .nes in games/. Read g_roms[g_rom_count] via select_game().
struct RomEntry
{
    const char   *name;   // display label (filename minus extension)
    const uint8_t *data;  // PROGMEM image, flash-mapped & directly readable
    size_t        len;    // image size in bytes
};

extern const RomEntry g_roms[];
extern const size_t   g_rom_count;
